### specific FRIS settings (path, files)
KEYWORDS:
    rig: Rig
    mod: Model
    text: Textures
    anim: Animation
    asset_rig_template: genericMale_Rig_Starter
    asset_name_template: genericMale
    bindPose_pattern: _Bindpose
    item_thumbn_sufix: '_thumbnail.jpg'
    real_depot_fol_root: core-content-art-source
    maped_depot_fol_root: source
    local_fol_root: ContentSource
Paths:
    Rig_Char_Path:        /ContentSource/Character/{char_na}/Maya/{char_na}_Rig.ma
    Mod_Char_Path:        /ContentSource/Character/{char_na}/Maya/{char_na}_Model.ma
    RigTemplateMalePath:  /ContentSource/Character/genericMale/Maya/genericMale_Rig_Starter.ma
    AnimRigPath:          /ContentSource/Character/{anim_char}/Maya/{anim_char}_Bindpose.ma
    AnimRigPath_template: /ContentSource/Character/genericMale/Maya/genericMale_Bindpose.ma
    ModTemplateMalePath:  /ContentSource/Character/genericMale/Maya/genericMale_Model_Starter.ma
    Char_Thumb_Path:      /ContentSource/Character/{char_na}/{char_na}_thumbnail.jpg
    Anim_Path:            /ContentSource/Animation/{subpath}{anim_na}_v000.ma
    Anim_Root:            /ContentSource/Animation/
    #Unreal_Anim_Root:     /ContentSource/Content/Sim/Characters/Generic/Art/Anim/
List:
    area_assets_ls: [ 'Rig', 'Model' , 'Textures']
    area_anim_ls: [ 'Animation']